## Disciplina - Introdução a Ciência de Dados - Univesp
## Exercícios de Apoio da Semana 2

### 1 - Carregue as bibliotecas NumPy e Pandas

In [76]:
import numpy as np
import pandas as pd

### 2 - Crie um NDArray com os seguintes valores [1, 2.5, 7, -78, -0.9, 130, 25]

In [79]:
valores = [1, 2.5, 7, -78, -0.9, 130, 25]
dadosArray = np.array(valores)
dadosArray

array([  1. ,   2.5,   7. , -78. ,  -0.9, 130. ,  25. ])

### 3 - Crie um NDArray com os valores de 0 a 10

In [82]:
valores = np.arange(11)
valores

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 4 – Crie um NDArray de dimensão 2x5 com valores 1

In [85]:
valores = np.ones((2,5))
valores

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 5 – Crie um NDArray com valores de 1 a 100, com intervalos de 3 em 3.

In [88]:
valores = np.arange(1,100,3)
valores

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

### 6 – Mostre as raízes quadradas dos valores do NDArray criado no exercícios 5.

In [91]:
raizes = np.sqrt(valores)
raizes

array([1.        , 2.        , 2.64575131, 3.16227766, 3.60555128,
       4.        , 4.35889894, 4.69041576, 5.        , 5.29150262,
       5.56776436, 5.83095189, 6.08276253, 6.32455532, 6.55743852,
       6.78232998, 7.        , 7.21110255, 7.41619849, 7.61577311,
       7.81024968, 8.        , 8.18535277, 8.36660027, 8.54400375,
       8.71779789, 8.88819442, 9.05538514, 9.21954446, 9.38083152,
       9.53939201, 9.69535971, 9.8488578 ])

### 7 – Altere a décima posição do NDArray criado no exercício 5 com o dobro do seu valor.

In [94]:
valores[9] = valores[9]*2
valores

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 56, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

### 8 – Execute o comando para criar um Dataframe com os dados disponíveis no notebook.

In [29]:
dados={'Empresa':['Microsoft', 'Google','Univesp','NVData Analytics','Power Bi Experience','USP'], 'Qtde Func':[1000, 1500,500, 100,100,499], 'Site':['https://www.microsoft.com/pt-br','https://www.google.com/','https://univesp.br/','https://www.nvdata.com.br/','https://powerbiexperience.com/pt/','https://www.usp.br/'],'Instagram':['@microsoft','@google','@univespoficial','@nv_data','@leokarpa','@usp.oficial'],'Criação':[1975,1998,2012,2019,2016,1934], 'País':['EUA','EUA','Brasil','Brasil','Brasil','Brasil']}

In [97]:
df = pd.DataFrame(dados)
df

Empresa  Qtde Func                               Site  \
0            Microsoft       1000    https://www.microsoft.com/pt-br   
1               Google       1500            https://www.google.com/   
2              Univesp        500                https://univesp.br/   
3     NVData Analytics        100         https://www.nvdata.com.br/   
4  Power Bi Experience        100  https://powerbiexperience.com/pt/   
5                  USP        499                https://www.usp.br/   

         Instagram  Criação    País  
0       @microsoft     1975     EUA  
1          @google     1998     EUA  
2  @univespoficial     2012  Brasil  
3         @nv_data     2019  Brasil  
4        @leokarpa     2016  Brasil  
5     @usp.oficial     1934  Brasil

### 9 – Execute um comando que seja possível identificar qual a média da quantidade de funcionários que as empresas listadas tem. Informe também a soma dos funcionários que as empresas tem.


In [117]:
print("Media: ", df['Qtde Func'].sum()/df['Empresa'].count())
print("Soma total: ", df['Qtde Func'].sum())

Media:  616.5
Soma total:  3699


### 10 – Mostre as primeiras 3 linhas do dataframe.

In [119]:
df.head(3)

Empresa  Qtde Func                             Site        Instagram  \
0  Microsoft       1000  https://www.microsoft.com/pt-br       @microsoft   
1     Google       1500          https://www.google.com/          @google   
2    Univesp        500              https://univesp.br/  @univespoficial   

   Criação    País  
0     1975     EUA  
1     1998     EUA  
2     2012  Brasil

### 11 – Mostre as últimas 3 linhas do dataframe.

In [123]:
df.tail(3)

Empresa  Qtde Func                               Site  \
3     NVData Analytics        100         https://www.nvdata.com.br/   
4  Power Bi Experience        100  https://powerbiexperience.com/pt/   
5                  USP        499                https://www.usp.br/   

      Instagram  Criação    País  
3      @nv_data     2019  Brasil  
4     @leokarpa     2016  Brasil  
5  @usp.oficial     1934  Brasil

### 12 – Liste apenas as linhas em que as empresas foram criadas nos últimos 10 anos. Informe a quantidade de registros.

In [125]:
df[df['Criação']>=2014]

Empresa  Qtde Func                               Site  \
3     NVData Analytics        100         https://www.nvdata.com.br/   
4  Power Bi Experience        100  https://powerbiexperience.com/pt/   

   Instagram  Criação    País  
3   @nv_data     2019  Brasil  
4  @leokarpa     2016  Brasil

### 13 – Vamos imaginar que em todas as empresas exista 1 chefe para cada 23 funcionários. Crie uma coluna que mostre a quantidade de chefes que cada empresa teria e depois informe quantos chefes teríamos ao todo. (os valores não precisam ser números inteiros, é apenas uma estimativa).


In [127]:
df['Chefes']=df['Qtde Func']/23
df

Empresa  Qtde Func                               Site  \
0            Microsoft       1000    https://www.microsoft.com/pt-br   
1               Google       1500            https://www.google.com/   
2              Univesp        500                https://univesp.br/   
3     NVData Analytics        100         https://www.nvdata.com.br/   
4  Power Bi Experience        100  https://powerbiexperience.com/pt/   
5                  USP        499                https://www.usp.br/   

         Instagram  Criação    País     Chefes  
0       @microsoft     1975     EUA  43.478261  
1          @google     1998     EUA  65.217391  
2  @univespoficial     2012  Brasil  21.739130  
3         @nv_data     2019  Brasil   4.347826  
4        @leokarpa     2016  Brasil   4.347826  
5     @usp.oficial     1934  Brasil  21.695652

In [129]:
df['Chefes'].sum()

160.82608695652175